### ISSUE TITLE
Store odysee auth token instead of creating a new user every time

### ISSUE THREAD

**Issue by lyoshenka** [keikari/Quadratic-funding-calculator#1]
This call creates a new user every time you call it. Instead, store the token locally and only do this if the local token is not found or doesn't work.

https://github.com/keikari/Quadratic-funding-calculator/blob/06f32c2ae08ddc41e14da6da7cf218dfbd0522f8/quadratic-funding-calculator.py#L25

**Comment by keikari** [comment]
Now it should store that to a file and try to initially use it.
https://github.com/keikari/Quadratic-funding-calculator/commit/9574356180c3057fabefca81b7313e1ab1d84bdf#diff-228c03491e7e7428d875011392e90d3a8a944e382081988b51b20e9502a897a1
